version: '3.4'

services:

  webshop.db:
    environment:
      - ACCEPT_EULA="Y"
      - MSSQL_SA_PASSWORD=MSSQLpasswd2022
    ports:
      - "1433:1433"

  webshop.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  webshop.ui:
    ports:
      - "5002:3000"
    environment:
      #Fixes bug where websocket connection is fixed to default port 3000
      - WDS_SOCKET_PORT=0
      - REACT_APP_API_URL=/api

  proxy:
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"